version: '2.1'
services:
  integration-test-runner:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GITLAB_BASE_URL=https://gitlab.com/api/v4
      - GITHUB_TOKEN=$GITHUB_TOKEN
      - GITHUB_SECRET=$GITHUB_SECRET
      - GITLAB_TOKEN=$GITLAB_TOKEN
    # volumes:
    #   - <path/to/key>:/root/.ssh/id_rsa
    #   - <path/to/key.pub>:/root/.ssh/id_rsa.pub
