apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-test-runner-deployment
  labels:
    app: integration-test-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-test-runner
  template:
    metadata:
      labels:
        app: integration-test-runner
    spec:
      containers:
      - name: integration-test-runner
        image: integration-test-runner:master
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
      envFrom:
        - secretRef:
          name: integration-test-runner-secrets
